// ignore_for_file: constant_identifier_names

const String FLUTTER_CHANNEL_NAME = "com.doomscroll.checkapp";
const String CHANNEL_DETECT_METHOD = "DETECT_APP";
const String CHANNEL_OVERLAY_PERMISSION = "REQUEST_OVERLAY_PERMISSION";
const String CHANNEL_USAGE_PERMISSION = "REQUEST_USAGE_PERMISSION";
const String GET_PLATFORM_VERSION = "getPlatformVersion";
const String REQUEST_NOTIFICATION_PERMISSION =
    "REQUEST_NOTIFICATION_PERMISSION";
    const  String REQUEST_BACKGROUND_PERMISSION = "REQUEST_BACKGROUND_PERMISSION";
const String GET_LAUNCHABLE_APPLICATIONS = "GET_LAUNCHABLE_APPLICATIONS";
    const  String REQUEST_LOCATION_PERMISSION = "REQUEST_LOCATION_PERMISSION";
    const  String DETECT_LOCATION_PERMISSION = "DETECT_LOCATION_PERMISSION";
