// ignore_for_file: constant_identifier_names

const String FLUTTER_CHANNEL_NAME = "com.doomscroll.checkapp";
const String CHANNEL_DETECT_METHOD = "DETECT_APP";
const String CHECK_OVERLAY_PERMISSION = "CHECK_OVERLAY_PERMISSION";
const String REQUEST_OVERLAY_PERMISSION = "REQUEST_OVERLAY_PERMISSION";
const String CHECK_USAGE_PERMISSION = "CHECK_USAGE_PERMISSION";
const String REQUEST_USAGE_PERMISSION = "REQUEST_USAGE_PERMISSION";
const String GET_PLATFORM_VERSION = "getPlatformVersion";
const String CHECK_NOTIFICATION_PERMISSION = "CHECK_NOTIFICATION_PERMISSION";
const String REQUEST_NOTIFICATION_PERMISSION =
    "REQUEST_NOTIFICATION_PERMISSION";
const String CHECK_BACKGROUND_PERMISSION = "CHECK_BACKGROUND_PERMISSION";
const String REQUEST_BACKGROUND_PERMISSION = "REQUEST_BACKGROUND_PERMISSION";
const String GET_LAUNCHABLE_APPLICATIONS = "GET_LAUNCHABLE_APPLICATIONS";
const String REQUEST_LOCATION_PERMISSION = "REQUEST_LOCATION_PERMISSION";
const String CHECK_LOCATION_PERMISSION = "CHECK_LOCATION_PERMISSION";
