name: CI
on: [push]
jobs:
  unit testing:
    runs-on: ubuntu-latest
    steps:
      - name: Clone plugin repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter --version


    name: run unit tests
    steps:
      - name: run for flutter plugin
        run: flutter test
      - name: run for example
        run: |
          cd example
          flutter test
    name: run android tests
    uses: actions/checkout@v4

    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: run example app tests
        run: |
          cd example/android
          ./gradlew test

