name: CI
on: [push]
jobs:
  android_unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: "stable"

      - run: flutter --version
      - run: flutter pub get
        working-directory: example

      - name: Create local.properties
        run: |
          echo "sdk.dir=${{ env.ANDROID_SDK_ROOT }}" > example/android/local.properties
          echo "flutter.minSdkVersion=29" >> example/android/local.properties
          echo "flutter.compileSdkVersion=33" >> example/android/local.properties
          echo "flutter.targetSdkVersion=33" >> example/android/local.properties
          echo "flutter.sdk=${{ env.FLUTTER_ROOT }}" >> example/android/local.properties

      - name: Run Android test(s) for plugin example
        run: gradle --project-dir ./example/android --no-daemon test
  unit_test_flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter --version

      - name: Run unit tests for Flutter plugin
        run: flutter test

      - name: Run unit tests for example app
        run: |
          cd example
          flutter test
