name: CI
on: [push]
jobs:
  setup:
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter --version
  run unit tests:
    steps:
      - name: run for flutter plugin
        run: flutter test
      - name: run for example
        run: |
          cd example
          flutter test
  run android tests:
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: run example app tests
        run: |
          cd example/android
          ./gradlew test

