name: CI
on: [push]
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter --version

      - name: Run unit tests for Flutter plugin
        run: flutter test

      - name: Run unit tests for example app
        run: |
          cd example
          flutter test

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Run Android tests for example app
        run: |
          cd example/android
          chmod +x ./gradlew
          ./gradlew test


