name: CI
on: [push]
jobs:
  unit_test_flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter --version

      - name: Run unit tests for Flutter plugin
        run: flutter test

      - name: Run unit tests for example app
        run: |
          cd example
          flutter test

unit_test_android:
  runs-on: ubuntu-latest
  steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.22.2
    - run: |
        flutter --version
        flutter pub get
        cd example
        flutter pub get
        cd ..

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Create local.properties
      run: |
        echo "sdk.dir=${{ env.ANDROID_SDK_ROOT }}" > example/android/local.properties
        echo "flutter.minSdkVersion=29" >> example/android/local.properties
        echo "flutter.compileSdkVersion=33" >> example/android/local.properties
        echo "flutter.targetSdkVersion=33" >> example/android/local.properties

    - name: Add Android SDK tools to PATH
      run: |
        echo "${{ env.ANDROID_SDK_ROOT }}/tools" >> $GITHUB_PATH
        echo "${{ env.ANDROID_SDK_ROOT }}/platform-tools" >> $GITHUB_PATH

    # Execute unit tests
    - name: Unit Test
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
      run: |
        cd example/android
        gradle wrapper
        ./gradlew testDebugUnitTest

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless